apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: pqc-digital-twin
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: pqc-migration-digital-twin
data:
  GO_SERVICES_HOST: "go-services"
