apiVersion: v1
kind: ConfigMap
metadata:
  name: go-services-config
  namespace: pqc-digital-twin
  labels:
    app.kubernetes.io/name: go-services
    app.kubernetes.io/part-of: pqc-migration-digital-twin
data:
  DISCOVERY_BASE_URL: "http://go-services:8081"
  PYTHON_BASE_URL: "http://python-services:8082"
  RUST_BASE_URL: "http://rust-risk:8083"
  QASM_BASE_URL: "http://python-services:8084"
