apiVersion: v1
kind: Service
metadata:
  name: go-services
  namespace: pqc-digital-twin
  labels:
    app.kubernetes.io/name: go-services
    app.kubernetes.io/part-of: pqc-migration-digital-twin
spec:
  selector:
    app.kubernetes.io/name: go-services
  ports:
    - name: gateway
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: discovery
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
